# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Inuktitut spellchecker"
iu = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Inuktitut, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
iu = "TRANSLATE: A spellchecker for Inuktitut, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.iu"

[windows]
system_product_code = "{28F4EF3A-BE55-4273-A30F-A0BD363CEA9E}_is1"
legacy_product_codes = [
    { value = "23C1A974-7889-4AD4-BE09-F89AB1F2E210", kind = "nsis" },
    { value = "AA091315-7297-4EB2-89F1-6AB5069556D8", kind = "nsis" }
]

[package.speller]
name = "Inuktitut"
version = "0.1.1"

[package.grammar]
name = "Inuktitut"
version = "0.1.0"

[package.tts-text-proc]
name = "Inuktitut"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
